runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /(.*\.(gif|png|svg|jpeg|jpg|scss|css|js|ico|ttf|woff|woff2|otf|xls|xlsx))$
    static_files: dist/\1
    upload: dist/(.*)
  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html
  - url: /
    static_dir: dist
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE